services:
 web:
   build: .
   working_dir: /data
   command: python produto.py
   links:
    - db
   volumes:
    - .:/data
   ports:
    - "5006:5006"

 db:
   image: mysql:5.7
   environment:
      MYSQL_ROOT_PASSWORD: mudar123
   ports:
    - "3309:3309"
